version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file: .env

  nginx_rp:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT:-8080}:${NGINX_PORT:-80}
    env_file:
      - .env

  auth:
    restart: always
    build: .
    working_dir: /usr/app/dir
    #command: ./start_service.sh auth
    volumes:
      - .:/usr/app/dir
    env_file:
      - .env
    depends_on:
      - db